services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: landing-venta-tours
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 9342
      RUN_DB_GENERATE: "false"
      RUN_DB_MIGRATIONS: "false"
      RUN_DB_PUSH: "false"
    ports:
      - "9342:9342"
    volumes:
      - ./uploads:/app/uploads
